version: '2'
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn playlister.wsgi:application -w 2 -b :80"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "80"
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    container_name: ps01
    env_file: .env