version: '2'
services:  
  nginx:
    image: jwilder/nginx-proxy
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - plist
    links:
      - plist
      - main
  plist:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn playlister.wsgi:application -w 2 -b :8080"
    depends_on:
      - db
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
    environment:
    - "VIRTUAL_HOST=playlists.localhost"
  db:
    image: postgres:latest
    container_name: ps01
    env_file: .env
  main:
    container_name: m01
    image: snurton/nathanieloon.com
    ports:
      - "8000:8000"
    environment:
    - "VIRTUAL_HOST=localhost"